"""Inicial migration

Revision ID: ea1003f7c7db
Revises: 
Create Date: 2025-10-21 19:53:44.263347

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea1003f7c7db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genero',
    sa.Column('id_genero', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id_genero')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_completo', sa.String(length=100), nullable=False),
    sa.Column('correo', sa.String(length=250), nullable=False),
    sa.Column('contrasena', sa.String(length=256), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('cancion',
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('artista', sa.String(length=100), nullable=False),
    sa.Column('duracion_segundos', sa.Integer(), nullable=True),
    sa.Column('tamano_mb', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('calidad_kbps', sa.Integer(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('id_genero', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_genero'], ['genero.id_genero'], ),
    sa.PrimaryKeyConstraint('id_cancion')
    )
    op.create_table('pedido',
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('fecha_pedido', sa.DateTime(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_pedido')
    )
    op.create_table('proveedor',
    sa.Column('id_proveedor', sa.Integer(), nullable=False),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre_tienda', sa.String(length=100), nullable=False),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_proveedor')
    )
    op.create_table('recopilacion',
    sa.Column('id_recopilacion', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('es_publica', sa.Boolean(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_recopilacion')
    )
    op.create_table('cancion_recopilacion',
    sa.Column('id_recopilacion', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_recopilacion'], ['recopilacion.id_recopilacion'], ),
    sa.PrimaryKeyConstraint('id_recopilacion', 'id_cancion')
    )
    op.create_table('vinilo',
    sa.Column('id_vinilo', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('artista', sa.String(length=100), nullable=True),
    sa.Column('año_salida', sa.Date(), nullable=True),
    sa.Column('precio', sa.Numeric(precision=6, scale=2), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('id_proveedor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_proveedor'], ['proveedor.id_proveedor'], ),
    sa.PrimaryKeyConstraint('id_vinilo')
    )
    op.create_table('cancion_vinilo',
    sa.Column('id_vinilo', sa.Integer(), nullable=False),
    sa.Column('id_cancion', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cancion'], ['cancion.id_cancion'], ),
    sa.ForeignKeyConstraint(['id_vinilo'], ['vinilo.id_vinilo'], ),
    sa.PrimaryKeyConstraint('id_vinilo', 'id_cancion')
    )
    op.create_table('detalle_pedido',
    sa.Column('id_detalle', sa.Integer(), nullable=False),
    sa.Column('id_pedido', sa.Integer(), nullable=False),
    sa.Column('id_vinilo', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unitario', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_pedido'], ['pedido.id_pedido'], ),
    sa.ForeignKeyConstraint(['id_vinilo'], ['vinilo.id_vinilo'], ),
    sa.PrimaryKeyConstraint('id_detalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_pedido')
    op.drop_table('cancion_vinilo')
    op.drop_table('vinilo')
    op.drop_table('cancion_recopilacion')
    op.drop_table('recopilacion')
    op.drop_table('proveedor')
    op.drop_table('pedido')
    op.drop_table('cancion')
    op.drop_table('usuario')
    op.drop_table('genero')
    # ### end Alembic commands ###
